package cloud.autotests.tests;

import io.qameta.allure.Description;
import org.junit.jupiter.api.*;

import static com.codeborne.selenide.Selenide.*;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class AppTests extends TestBase {
    @Test
    @Description("Soon to be implemented by QA.GURU engineers")
    @DisplayName("can't login with not registered user to https://www.busuu.com/")
    void generatedTest() {
        step("Open https://www.busuu.com/", () -> {
            // todo
        });

        step("Try to login with not registered user", () -> {
            // todo
        });

        step("Assert stayed on same page with some error message", () -> {
            // todo
        });
    }

    @Test
    @Description("Autogenerated, because your test steps contain text 'http...' and the page has &lt;title&gt;")
    @DisplayName("Page title test")
    void titleTest() {
        step("Open url 'https://www.busuu.com/'", () ->
            open("https://www.busuu.com/"));

        step("Checking that the page title has is 'Busuu - Learn languages online: start for free'", () -> {
            String expectedTitle = "Busuu - Learn languages online: start for free";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }
}